// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2025, 10, 14, 3, 32, 52, 681, DateTimeKind.Utc).AddTicks(3907),
                            Email = "manu@gmail.com",
                            FirstName = "Manuel",
                            HashedPassword = "manu1234",
                            LastName = "Cecarelli",
                            Role = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2025, 10, 14, 3, 32, 52, 681, DateTimeKind.Utc).AddTicks(3913),
                            Email = "fede@gmail.com",
                            FirstName = "Federico",
                            HashedPassword = "fede1234",
                            LastName = "Perez",
                            Role = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2025, 10, 14, 3, 32, 52, 681, DateTimeKind.Utc).AddTicks(3914),
                            Email = "viky@gmail.com",
                            FirstName = "Victoria",
                            HashedPassword = "viky1234",
                            LastName = "Lopez",
                            Role = 2,
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
